//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Job_Description { get; set; }
        public string Number { get; set; }
        public decimal HourlyPay { get; set; }
        public decimal Bonus { get; set; }
        public int EmployeeTypeId { get; set; }
        public Nullable<decimal> HouseAllowance { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public string ComputerDetail { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
